name: Automated Release

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine Version Bump
      id: bump_type
      run: |
        BODY="${{ github.event.pull_request.body }}"
        if [[ "$BODY" == *"[x] ðŸ’¥ Breaking change"* ]]; then
          echo "type=major" >> $GITHUB_OUTPUT
        elif [[ "$BODY" == *"[x] âœ¨ New feature"* ]]; then
          echo "type=minor" >> $GITHUB_OUTPUT
        elif [[ "$BODY" == *"[x] ðŸ› Bug fix"* ]]; then
          echo "type=patch" >> $GITHUB_OUTPUT
        else
          echo "type=none" >> $GITHUB_OUTPUT
        fi

    - name: Create Tag
      if: steps.bump_type.outputs.type != 'none'
      id: tag_version
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: ${{ steps.bump_type.outputs.type }}
        WITH_V: true

    - name: set up JDK 17
      if: steps.bump_type.outputs.type != 'none'
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      if: steps.bump_type.outputs.type != 'none'
      run: chmod +x gradlew

    - name: Decode Keystore
      if: steps.bump_type.outputs.type != 'none'
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > app/release.keystore

    - name: Build Release APK
      if: steps.bump_type.outputs.type != 'none'
      env:
        KEYSTORE_PATH: release.keystore
        KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Create GitHub Release
      if: steps.bump_type.outputs.type != 'none'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        files: app/release/app-release.apk
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
